baseURL = "https://dwarkeshpatel.com"
title = "Dwarkesh Patel"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = 'UA-207697668-1'

[params]
  dark = "auto"
  highlight = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "twitter"
    name = "twitter"
    title = "twitter"
    url = "https://twitter.com/dwarkesh_sp"
    weight = 15

  [[menu.main]]
    identifier = "subscribe"
    name = "subscribe"
    title = "subscribe"
    url = "https://dwarkesh.substack.com/subscribe"
    weight = 20
[permalinks]
  posts = "/:filename/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
